const ifido_and_ifidid = [
    ['I think I left my watch at your house. Have you seen it? –No, but I’ll look when I get home. If I find it, I’ll tell you. ⌚', 'Creo que dejé mi reloj en tu casa. ¿Lo has visto? –No, pero buscaré cuando llegue a casa. Si lo encuentro, te lo diré. ⌚'],
    ['If I found a wallet in the street, I’d take it to the police station. 🚓', 'Si encontrara una cartera en la calle, la llevaría a la comisaría de policía. 🚓'],
    ['What would you do if you won a million dollars? 💰', '¿Qué harías si ganaras un millón de dólares? 💰'],
    ['I don’t really want to go to their party, but I probably will go. They’d be hurt if I didn’t go. 🎉', 'Realmente no quiero ir a su fiesta, pero probablemente vaya. Les dolería si no fuera. 🎉'],
    ['If there was an election tomorrow, who would you vote for? 🗳️', 'Si hubiera una elección mañana, ¿por quién votarías? 🗳️'],
    ['If there were a party tomorrow, would you go? 🎈', 'Si hubiera una fiesta mañana, ¿irías? 🎈'],
    ['I’d be very frightened if somebody pointed a gun at me. 🔫', 'Estaría muy asustado si alguien me apuntara con una pistola. 🔫'],
    ['If I didn’t go to their party, they’d be hurt. 😔', 'Si no voy a su fiesta, estarían heridos. 😔'],
    ['If you got more exercise, you’d feel better. 💪', 'Si haces más ejercicio, te sentirías mejor. 💪'],
    ['I’m not tired. If I went to bed now, I wouldn’t sleep. 😴', 'No estoy cansado. Si me fuera a la cama ahora, no dormiría. 😴'],
    ['Would you mind if I used your phone? 📱', '¿Te importaría si uso tu teléfono? 📱'],
    ['If you got more exercise, you might feel better. 💪', 'Si haces más ejercicio, es posible que te sientas mejor. 💪'],
    ['If it stopped raining, we could go out. ☔', 'Si dejara de llover, podríamos salir. ☔'],
    ['They’d be hurt if I didn’t go to their party. 😔', 'Estarían heridos si no fuera a su fiesta. 😔'],
    ['What would you do if you were bitten by a snake? 🐍', '¿Qué harías si te mordiera una serpiente? 🐍'],    
]
const ifiknew_iwhishiknew = [
    ['If I knew his phone number, I would call him. ☎️', 'Si supiera su número de teléfono, lo llamaría. ☎️'],
    ['Tom would read more if he had more time. 📚', 'Tom leería más si tuviera más tiempo. 📚'],
    ['If I didn’t want to go to the party, I wouldn’t go. 🎉', 'Si no quisiera ir a la fiesta, no iría. 🎉'],
    ['We wouldn’t have any money if we didn’t work. 💰', 'No tendríamos dinero si no trabajáramos. 💰'],
    ['If you were in my position, what would you do? 🤔', 'Si estuvieras en mi posición, ¿qué harías? 🤔'],
    ['It’s a shame you can’t drive. It would be helpful if you could. 🚗', 'Es una lástima que no puedas conducir. Sería útil si pudieras. 🚗'],
    ['I wish I knew Paul’s phone number. 📞', 'Ojalá supiera el número de teléfono de Paul. 📞'],
    ['Do you ever wish you could fly? ✈️', '¿Alguna vez deseas poder volar? ✈️'],
    ['It rains a lot here. I wish It didn’t rain so often. 🌧️', 'Llueve mucho aquí. Ojalá no lloviera tan seguido. 🌧️'],
    ['It’s very crowded here. I wish there weren’t so many people. 🙇‍♂️', 'Está muy lleno aquí. Ojalá no hubiera tanta gente. 🙇‍♂️'],
    ['I wish I didn’t have to work tomorrow, but unfortunately, I do. 😔', 'Ojalá no tuviera que trabajar mañana, pero desafortunadamente, sí. 😔'],
    ['If I was you, I wouldn’t buy that coat. 👘', 'Si fuera tú, no compraría ese abrigo. 👘'],
    ['If I were you, I wouldn’t buy that car. 🚗', 'Si fuera tú, no compraría ese coche. 🚗'],
    ['I’d go out if it wasn’t so cold. ❄️', 'Saliría si no hiciera tanto frío. ❄️'],
    ['I wish Carol was here. 🙇‍♀️', 'Ojalá Carol estuviera aquí. 🙇‍♀️'],
    ['I wish Diego were here. 🙇‍♂️', 'Ojalá Diego estuviera aquí. 🙇‍♂️'],
    ['If I were rich, I would have a yacht. ⛵', 'Si fuera rico, tendría un yate. ⛵'],
    ['I wish I had something to read. 📖', 'Ojalá tuviera algo que leer. 📖'],
    ['You could get a better job. 💼', 'Podrías conseguir un trabajo mejor. 💼'],
    ['If you could use a computer. 💻', 'Si pudieras usar una computadora. 💻'],
]
const ifIhadknown= [
    ['If I had known you were in the hospital, I would have gone to see you. 🏥', 'Si hubiera sabido que estabas en el hospital, habría ido a verte. 🏥'],
    ['I didn’t see you when you passed me in the street. If I’d seen you, of course I would have said hello. 🚶‍♂️', 'No te vi cuando pasaste por la calle. Si te hubiera visto, por supuesto te habría saludado. 🚶‍♂️'],
    ['I didn’t go out last night. I would have gone out if I hadn’t been so tired. 😴', 'No salí anoche. Habría salido si no hubiera estado tan cansado. 😴'],
    ['If he had been looking where he was going, he wouldn’t have walked into the wall. 🚶‍♂️', 'Si hubiera estado mirando hacia dónde iba, no habría chocado contra la pared. 🚶‍♂️'],
    ['The view was wonderful. If I’d had a camera, I would have taken some pictures. 📸', 'La vista era maravillosa. Si hubiera tenido una cámara, habría tomado algunas fotos. 📸'],
    ['I’m not hungry. If I were hungry, I would eat something. 🍽️', 'No tengo hambre. Si tuviera hambre, comería algo. 🍽️'],
    ['I wasn’t hungry. If I had been hungry, I would have eaten something. 🥪', 'No tenía hambre. Si hubiera tenido hambre, habría comido algo. 🥪'],
    ['I wish I’d known that Brian was sick. I would have gone to see him. 🤒', 'Ojalá hubiera sabido que Brian estaba enfermo. Habría ido a verlo. 🤒'],
    ['I feel sick. I wish I hadn’t eaten so much cake. 🍰', 'Me siento enfermo. Ojalá no hubiera comido tanto pastel. 🍰'],
    ['Do you wish you had studied science instead of languages? 📚', '¿Deseas haber estudiado ciencias en lugar de idiomas? 📚'],
    ['The weather was cold on our vacation. I wish It had been warmer. ☀️', 'El clima estaba frío en nuestras vacaciones. Ojalá hubiera sido más cálido. ☀️'],
    ['If I had gone to the party last night, I would be tired now. 😴', 'Si hubiera ido a la fiesta anoche, ahora estaría cansado. 😴'],
    ['If I had gone to the party last night, I would have met lots of people. 👥', 'Si hubiera ido a la fiesta anoche, habría conocido a mucha gente. 👥'],
]
const wish= [
    ['I wish you al the best in the future. 🌟', 'Te deseo todo lo mejor en el futuro. 🌟'],
    ['I saw Tim before the exam, and he wished me luck. 🍀', 'Vi a Tim antes del examen, y él me deseó suerte. 🍀'],
    ['I hope you get this letter before you leave the town. 📬', 'Espero que recibas esta carta antes de que te vayas del pueblo. 📬'],
    ['I wish you a pleasant stay here. 😊', 'Te deseo una estancia agradable aquí. 😊'],
    ['I hope you have pleasant stay here. 😊', 'Espero que tengas una estancia agradable aquí. 😊'],
    ['I wish I knew what to do about the problem. 🤔', 'Ojalá supiera qué hacer sobre el problema. 🤔'],
    ['I wish you didn’t have to go so soon. 😞', 'Ojalá no tuvieras que irte tan pronto. 😞'],
    ['Do you wish you lived near to the ocean? 🏖️', '¿Deseas vivir cerca del océano? 🏖️'],
    ['Jack’s going on a trip to Mexico soon. I wish I was going too. ✈️', 'Jack se va de viaje a México pronto. Ojalá yo también pudiera ir. ✈️'],
    ['I wish I’d known about the party. I would have gone if I’d known. 🎉', 'Ojalá hubiera sabido sobre la fiesta. Habría ido si lo hubiera sabido. 🎉'],
    ['It was a stupid thing to say. I wish I hadn’t said it. 🤦‍♂️', 'Fue una tontería decir eso. Ojalá no lo hubiera dicho. 🤦‍♂️'],
    ['I’m sorry I have to go. I wish I could stay longer. ⏳', 'Lo siento, tengo que irme. Ojalá pudiera quedarme más tiempo. ⏳'],
    ['I’ve met than man before. I wish I could remember his name. 🤔', 'He conocido a ese hombre antes. Ojalá pudiera recordar su nombre. 🤔'],
    ['I hear the party was great. I wish I could have gone. 🎉', 'Escuché que la fiesta estuvo genial. Ojalá hubiera podido ir. 🎉'],
    ['I wish it would stop raining. ☔', 'Ojalá dejara de llover. ☔'],
    ['The phone has been ringing for five minutes. I wish somebody would answer it. 📞', 'El teléfono ha estado sonando durante cinco minutos. Ojalá alguien contestara. 📞'],
    ['I wish you would do something instead of just sitting and doing nothing. 🛋️', 'Ojalá hicieras algo en lugar de simplemente sentarte y no hacer nada. 🛋️'],
    ['I wish you wouldn’t keep interrupting me. 🤐', 'Ojalá no siguieras interrumpiéndome. 🤐'],
    ['I wish Sarah would come. 🚶‍♀️', 'Ojalá Sarah viniera. 🚶‍♀️'],
    ['I wish Sara was here now. 🕰️', 'Ojalá Sara estuviera aquí ahora. 🕰️'],
    ['I wish somebody would buy me a car. 🚗', 'Ojalá alguien me comprara un coche. 🚗'],
    ['I wish I had a car. 🚗', 'Ojalá tuviera un coche. 🚗'],
]

export { ifido_and_ifidid, ifiknew_iwhishiknew, ifIhadknown, wish }