 const canCouldAndBeAbleTo = [
    ['We can see the ocean from our hotel window.', 'Podemos ver el océano desde la ventana de nuestro hotel. 🌊🏨'],
    ['I don’t have a pen. –You can use mine.', 'No tengo una pluma. - Puedes usar la mía. ✒️'],
    ['Can you speak any foreign languages?', '¿Puedes hablar algún idioma extranjero? 🌍🗣️'],
    ['I can come and help you tomorrow if you want.', 'Puedo venir y ayudarte mañana si quieres. 🤝📅'],
    ['The word “dream” can be a noun or a verb.', 'La palabra "sueño" puede ser un sustantivo o un verbo. 💭📖'],
    ['I’m afraid I can’t come to your party on Friday.', 'Me temo que no puedo ir a tu fiesta el viernes. 🎉🚫'],
    ['We are able to see the ocean from our hotel window.', 'Podemos ver el océano desde la ventana de nuestro hotel. 🌊🏨'],
    ['I haven’t been able to sleep recently.', 'No he podido dormir últimamente. 😴🚫'],
    ['Tom might be able to come tomorrow.', 'Tom podría venir mañana. 🤔📆'],
    ['Applicants for the job must be able to speak two foreign languages.', 'Los solicitantes para el trabajo deben poder hablar dos idiomas extranjeros. 💼🗣️'],
    ['We had a nice room in the hotel. We could see the ocean.', 'Tuvimos una habitación bonita en el hotel. Podíamos ver el océano. 🌅🏨'],
    ['As soon as I walked into the room, I could smell gas.', 'Tan pronto como entré en la habitación, pude oler gas. 👃🔥'],
    ['She spoke in a very soft voice, so I couldn’t understand what she said.', 'Hablaba con una voz muy suave, así que no podía entender lo que decía. 🗣️👂'],
    ['My grandfather could speak five languages.', 'Mi abuelo podía hablar cinco idiomas. 👴🗣️'],
    ['We were totally free. We could do what we wanted. (= we were allowed to do)', 'Éramos totalmente libres. Podíamos hacer lo que quisiéramos. (= nos permitían hacerlo) 🤸‍♂️🔓'],
    ['The fire spread through the building very quickly, but fortunately, everybody was able to escape / managed to escape.', 'El fuego se propagó por el edificio muy rápido, pero afortunadamente, todos pudieron escapar. 🏢🔥'],
    ['We didn’t know where David was, but we managed to find / were able to find him in the end.', 'No sabíamos dónde estaba David, pero logramos encontrarlo al final. 🕵️‍♂️🤝'],
    ['Jack was an excellent tennis player when he was younger. He could beat anybody.', 'Jack era un excelente jugador de tenis cuando era más joven. Podía vencer a cualquiera. 🎾🏆'],
    ['Jack and Ted played tennis yesterday. Ted played very well, but Jack managed to / was able to beat him.', 'Jack y Ted jugaron tenis ayer. Ted jugó muy bien, pero Jack logró vencerlo. 🎾🤼‍♂️'],
    ['My grandfather couldn’t swim.', 'Mi abuelo no sabía nadar. 🏊‍♂️🚫'],
    ['We looked for David everywhere, but we couldn’t find him.', 'Buscamos a David por todas partes, pero no pudimos encontrarlo. 🔍🤷‍♂️'],
    ['Ted played well, but he couldn’t beat Jack.', 'Ted jugó bien, pero no pudo vencer a Jack. 🎾🤷‍♂️'],    
]
 const couldAndCouldHaveDone = [
    ['What would you like to do tonight? –We could go to the movies.', '¿Qué te gustaría hacer esta noche? - Podríamos ir al cine. 🍿🎬'],
    ['When you go to New York next month, you could stay with Candice. –Yes, I guess I could.', 'Cuando vayas a Nueva York el próximo mes, podrías quedarte con Candice. - Sí, supongo que podría. 🗽🏠'],
    ['I’m so tired, I could sleep for a week.', 'Estoy tan cansado que podría dormir durante una semana. 😴📆'],
    ['I can stay with Candice when I go to New York.', 'Puedo quedarme con Candice cuando vaya a Nueva York. 🏠🗽'],
    ['Maybe I could stay with Candice when I go to New York.', 'Quizás podría quedarme con Candice cuando vaya a Nueva York. 🤔🗽'],
    ['This is a wonderful place. I could stay here forever.', 'Este es un lugar maravilloso. Podría quedarme aquí para siempre. 🌄🏡'],
    ['The story could be true, but I don’t think it is.', 'La historia podría ser verdad, pero no creo que lo sea. 📖🤷'],
    ["I don’t know what time Liz is coming. She could get here at any time.", 'No sé a qué hora vendrá Liz. Podría llegar en cualquier momento. ⌛🤔'],
    ['I’m so tired, I could have slept for a week.', 'Estoy tan cansado que podría haber dormido durante una semana. 😴📅'],
    ['The situation is bad, but it could be worse.', 'La situación es mala, pero podría ser peor. 📉🤷'],
    ['The situation was bad, but it could have been worse.', 'La situación era mala, pero podría haber sido peor. 📉🤷'],
    ['Why did you stay at a hotel when you were in New York? You could have stayed with Candice.', '¿Por qué te quedaste en un hotel cuando estabas en Nueva York? Podrías haber quedado con Candice. 🏨🗽'],
    ['I didn’t know that you wanted to go to the concert. I could have gotten you a free ticket.', 'No sabía que querías ir al concierto. Podría haberte conseguido una entrada gratuita. 🎫🤷'],
    ['Dave was lucky. He could have hurt himself when he fell, but he’s OK.', 'Dave tuvo suerte. Podría haberse lastimado cuando se cayó, pero está bien. 🍀🤕'],
    ["I couldn’t live in a big city. I’d hate it.", 'No podría vivir en una ciudad grande. Lo odiaría. 🌆😖'],
    ['Everything is fine right now. Things couldn’t be better.', 'Todo está bien ahora mismo. Las cosas no podrían ser mejores. 🌟👌'],
    ['We had a really good vacation. It couldn’t have been better.', 'Tuvimos unas vacaciones realmente buenas. No podrían haber sido mejores. 🏝️👌'],
    ['The trip was canceled last week. Paul couldn’t have gone anyway because he was sick.', 'El viaje fue cancelado la semana pasada. De todos modos, Paul no podría haber ido porque estaba enfermo. 🛑🤒'],
]
const  must = [
    ['My house is next to the freeway. –It must be very noisy.', 'Mi casa está al lado de la autopista. - Debe ser muy ruidoso. 🏠🛣️'],
    ['You’ve been traveling all day. You must be tired.', 'Has estado viajando todo el día. Debes estar cansado. ✈️😴'],
    ['Jim is a hard worker. –Jim? You must be joking. He’s very lazy.', 'Jim es trabajador. - ¿Jim? Debes estar bromeando. Es muy perezoso. 💼😆'],
    ['I’m sure Sally gave me her phone number. I must have it somewhere.', 'Estoy seguro de que Sally me dio su número de teléfono. Debo tenerlo en algún lugar. 📞🤔'],
    ['Their car isn’t outside their house. They must not be home.', 'Su auto no está afuera de su casa. Deben no estar en casa. 🏠🚗'],
    ["Brian said he would be here by 9:30. It's 10:00 now, and he’s never late. He must not be coming.", 'Brian dijo que estaría aquí para las 9:30. Son las 10:00 ahora, y nunca llega tarde. Debe ser que no viene. ⌚🤷'],
    ['They haven’t lived here very long. They must not know many people.', 'No han vivido aquí mucho tiempo. Deben no conocer a mucha gente. 🏡👥'],
    ['We used to live close to the freeway. –Did you? It must have been noisy.', 'Solíamos vivir cerca de la autopista. - ¿En serio? Debe haber sido ruidoso. 🛣️🤔'],
    ['There’s nobody at home. They must have gone out.', 'No hay nadie en casa. Deben haber salido. 🚶‍♂️🚪'],
    ['I’ve lost one of my gloves. I must have dropped it somewhere.', 'He perdido uno de mis guantes. Debo haberlo dejado caer en algún lugar. 🧤🤦‍♂️'],
    ['She walked past me without speaking. She must not have seen me.', 'Pasó por mi lado sin hablar. Debe ser que no me vio. 👀🚶‍♀️'],
    ['Tom walked into a wall. He must not have been looking where he was going.', 'Tom se chocó con una pared. Debe ser que no estaba mirando por dónde iba. 🚶‍♂️🤦‍♂️'],
    ['How can you say such a thing? You can’t be serious!', '¿Cómo puedes decir semejante cosa? ¡No puedes estar hablando en serio! 😮🤨'],
    ['Joe wants something to eat. –But he just had lunch. He can’t be hungry already.', 'Joe quiere algo para comer. - Pero acaba de almorzar. No puede tener hambre tan pronto. 🍔🤷'],
    ['I offered Bill something to eat, but he didn’t want anything. –He must not be hungry.', 'Le ofrecí algo de comer a Bill, pero no quería nada. - Debe ser que no tiene hambre. 🍽️🤔'],
]
 const mayAndMight1 = [
    ['I haven’t decided yet where to go on vacation. I may go to Hawaii. 🏝️', 'Todavía no he decidido a dónde ir de vacaciones. Puede que vaya a Hawái. 🏝️'],
    ['Take an umbrella with you. It might rain later. ☔', 'Lleva un paraguas contigo. Podría llover más tarde. ☔'],
    ['The bus isn’t always on time. We might have to wait a few minutes. ⌛', 'El autobús no siempre llega a tiempo. Podríamos tener que esperar unos minutos. ⌛'],
    ['Ann may not go out tonight. She isn’t feeling well. 🤒', 'Ann puede que no salga esta noche. No se siente bien. 🤒'],
    ['There might not be enough time to discuss everything at the meeting. ⏰', 'Puede que no haya suficiente tiempo para discutir todo en la reunión. ⏰'],
    ['I’ll be late this evening. ⏰', 'Llegaré tarde esta noche. ⏰'],
    ['I may be late this evening. ⏰', 'Puede que llegue tarde esta noche. ⏰'],
    ['I might be late this evening. ⏰', 'Podría llegar tarde esta noche. ⏰'],
    ['I may go to Hawaii / I might go to Hawaii 🛫', 'Puede que vaya a Hawái. / Podría ir a Hawái. 🛫'],
    ['Lisa might be able to help you / Lisa may be able to help you. 🤝', 'Lisa podría ayudarte / Lisa podría ser capaz de ayudarte. 🤝'],
    ['If I were in Tom’s position, I think I might look for another job. 💼', 'Si estuviera en la posición de Tom, creo que podría buscar otro trabajo. 💼'],
    ['Don’t call me at 8:30. I might be watching the game on TV. 📺', 'No me llames a las 8:30. Podría estar viendo el juego en la televisión. 📺'],
    ['I may be going to Hawaii in July. 🛫', 'Puede que vaya a Hawái en julio. 🛫'],
    ['What should we do? Should we walk? –We might as well. It’s a nice day, and I don’t want to wait here for an hour. 🚶‍♂️', '¿Qué deberíamos hacer? ¿Deberíamos caminar? –Podríamos hacerlo. Es un buen día y no quiero esperar aquí una hora. 🚶‍♂️'],
    ['You’ll have to wait two hours to see the doctor. –I might as well go home and come back. 🏥', 'Tendrás que esperar dos horas para ver al médico. –Podría volver a casa y regresar. 🏥'],
]
 const mayAndMight2 = [
    ['Where\'s Bob? –He may be in his office 🕵️‍♂️', '¿Dónde está Bob? –Él podría estar en su oficina. 🕵️‍♂️'],
    ['Where\'s Bob? –he might be having lunch. 🍽️', '¿Dónde está Bob? –Podría estar almorzando. 🍽️'],
    ['Where\'s Bob? –Ask Ann. She might know. 💁‍♀️', '¿Dónde está Bob? –Pregunta a Ann. Ella podría saber. 💁‍♀️'],
    ['It may be true / It might be true 🤷‍♂️', 'Podría ser verdad / Podría ser cierto. 🤷‍♂️'],
    ['She might know. / She may know. 💬', 'Ella podría saber. / Ella podría saber. 💬'],
    ['It may not be true. 🙅‍♂️', 'Podría no ser verdad. 🙅‍♂️'],
    ['She might not work here anymore. 🤔', 'Ella podría no trabajar aquí ya. 🤔'],
    ['I wonder why Kate didn’t answer the phone. –She may have been asleep. 😴', 'Me pregunto por qué Kate no contestó el teléfono. –Podría haber estado durmiendo. 😴'],
    ['I can’t find my bag anywhere. –You might have left it in the store. 🛍️', 'No puedo encontrar mi bolso en ninguna parte. –Podrías haberlo dejado en la tienda. 🛍️'],
    ['I was surprised that Sarah wasn’t at the meeting yesterday. –She might not have known about it. 😲', 'Me sorprendió que Sarah no estuviera en la reunión ayer. –Podría no haber sabido de eso. 😲'],
    ['I wonder why David was in such a bad mood yesterday. –He may not have been feeling well. 😞', 'Me pregunto por qué David estaba de tan mal humor ayer. –Puede que no se sintiera bien. 😞'],
    ['It’s a strange story, but it could be true. 🤨', 'Es una historia extraña, pero podría ser cierta. 🤨'],
    ['You could have left your bag in the store. 👜', 'Podrías haber dejado tu bolso en la tienda. 👜'],
    ['Sarah couldn’t have gotten my message. Otherwise, she would have called me. 📵', 'Sarah no podría haber recibido mi mensaje. De lo contrario, me habría llamado. 📵'],
    ['I wonder why Sarah hasn’t called me. I suppose she might not have gotten my message. 🤷‍♀️', 'Me pregunto por qué Sarah no me ha llamado. Supongo que podría no haber recibido mi mensaje. 🤷‍♀️'],
]
 const haveToAndMust = [
    ['You can’t turn right here. You have to turn left. ⬅️', 'No puedes girar a la derecha aquí. Tienes que girar a la izquierda. ⬅️'],
    ['I have to get up early tomorrow. My flight leaves at 7:30. ⏰', 'Tengo que levantarme temprano mañana. Mi vuelo sale a las 7:30. ⏰'],
    ['Jason can’t meet us tonight. He has to work late. 🕰️', 'Jason no puede encontrarnos esta noche. Él tiene que trabajar hasta tarde. 🕰️'],
    ['Last week Nicole broke her arm and had to go to the hospital. 💉', 'La semana pasada Nicole se rompió el brazo y tuvo que ir al hospital. 💉'],
    ['Have you ever had to go to the hospital? 🏥', '¿Alguna vez has tenido que ir al hospital? 🏥'],
    ['What do I have to do to get a driver’s license? 🚗', '¿Qué tengo que hacer para obtener una licencia de conducir? 🚗'],
    ['Does Kimberly have to work tomorrow? 📅', '¿Kimberly tiene que trabajar mañana? 📅'],
    ['Why did you have to leave early? ❓', '¿Por qué tuviste que salir temprano? ❓'],
    ['I don’t have to get up early tomorrow. ⏰', 'No tengo que levantarme temprano mañana. ⏰'],
    ['Kimberly doesn’t have to work on Saturdays. 📅', 'Kimberly no tiene que trabajar los sábados. 📅'],
    ['We didn’t have to pay to park the car. 💰', 'No tuvimos que pagar para estacionar el auto. 💰'],
    ['They can’t fix my computer, so I’ll have to buy a new one. 💻', 'No pueden arreglar mi computadora, así que tendré que comprar una nueva. 💻'],
    ['They can’t fix my car, so I’m going to have to buy a new one. 🚗', 'No pueden arreglar mi coche, así que voy a tener que comprar uno nuevo. 🚗'],
    ['I might have to leave the meeting early. ⌚', 'Podría tener que salir de la reunión temprano. ⌚'],
    ['I may have to leave the class early. ⌚', 'Puede que tenga que salir de la clase temprano. ⌚'],
    ['The economic situation is bad. The government must do something about it. 💼', 'La situación económica es mala. El gobierno debe hacer algo al respecto. 💼'],
    ['The pollution is terrible. The government hast to do something about it. 😷', 'La contaminación es terrible. El gobierno debe hacer algo al respecto. 😷'],
    ['Answer all the questions. You must write your answers in ink. ✒️', 'Responde todas las preguntas. Debes escribir tus respuestas con tinta. ✒️'],
    ['Applications for the job must be received by May 18. 📅', 'Las solicitudes para el trabajo deben recibirse antes del 18 de mayo. 📅'],
    ['Students must not use cellphones in class. 📵', 'Los estudiantes no deben usar teléfonos celulares en clase. 📵'],
    ['You must keep this a secret. You must not tell anybody. 🤫', 'Debes mantener esto en secreto. No debes contarle a nadie. 🤫'],
    ['You don’t have to tell Tim about what happened. I can tell him myself. (You don’t need to tell him, but it’s OK if you do)', 'No necesitas contarle a Tim lo que pasó. Puedo decírselo yo mismo. (No es necesario que se lo digas, pero está bien si lo haces)'],
    ['I’ve got to work tomorrow. / I have to work tomorrow. ⏳', 'Tengo que trabajar mañana. ⏳'],
    ['He’s got to visit his aunt tonight. / He has to visit his aunt tonight. 🌙', 'Él tiene que visitar a su tía esta noche. 🌙'],
]
 const Should = [
    ['You look tired. You should go to bed. 😴', 'Te ves cansado. Deberías ir a dormir. 😴'],
    ['The government should do more to reduce crime. 👮‍♂️', 'El gobierno debería hacer más para reducir el crimen. 👮‍♂️'],
    ['Should we invite Susan to the party? –Yes, I think we should. 🎉', '¿Deberíamos invitar a Susan a la fiesta? –Sí, creo que deberíamos. 🎉'],
    ['I think the government should do more to reduce crime. 👮‍♀️', 'Creo que el gobierno debería hacer más para reducir el crimen. 👮‍♀️'],
    ['I don’t think you should work so hard. 💼', 'No creo que debas trabajar tan duro. 💼'],
    ['Do you think I should apply for this job? –Yes, I think you should. 💼', '¿Crees que debería postularme para este trabajo? –Sí, creo que deberías. 💼'],
    ['You shouldn’t believe everything you read in the newspapers. 📰', 'No deberías creer todo lo que lees en los periódicos. 📰'],
    ['You should apologize. 🙏', 'Deberías disculparte. 🙏'],
    ['You must apologize. / You have to apologize. 🚫', 'Debes disculparte. / Tienes que disculparte. 🚫'],
    ['I wonder where Liz is. She should be here by now. 🤔', 'Me pregunto dónde está Liz. Debería estar aquí para ahora. 🤔'],
    ['The price on this package is wrong. It should be $1.29, not $1.59. 💰', 'El precio en este paquete está mal. Debería ser $1.29, no $1.59. 💰'],
    ['The man on the motorcycle should be wearing a helmet. 🏍️', 'El hombre en la motocicleta debería estar usando un casco. 🏍️'],
    ['She’s been studying hard for the exam, so she should pass. 📚', 'Ha estado estudiando mucho para el examen, así que debería aprobar. 📚'],
    ['There are plenty of hotels in this city. It shouldn’t be hard to find a place to stay. 🏨', 'Hay muchos hoteles en esta ciudad. No debería ser difícil encontrar un lugar para quedarse. 🏨'],
    ['You missed a great party last night. You should have come. Why didn’t you? 🎉', 'Te perdiste una gran fiesta anoche. Deberías haber venido. ¿Por qué no lo hiciste? 🎉'],
    ['I wonder why they’re so late. They should have been here an hour ago. ⌚', 'Me pregunto por qué están tan tarde. Deberían haber estado aquí hace una hora. ⌚'],
    ['I feel sick. I shouldn’t have eaten so much. 🤢', 'Me siento enfermo. No debería haber comido tanto. 🤢'],
    ['She shouldn’t have been listening to our conversation. It was private. 👂', 'No debería haber estado escuchando nuestra conversación. Era privada. 👂'],
    ['You look tired. You should go to bed now. 😴', 'Te ves cansado. Deberías ir a la cama ahora. 😴'],
    ['You went to bed very late last night. You should have gone to bed earlier. 🌙', 'Te fuiste a la cama muy tarde anoche. Deberías haberte acostado más temprano. 🌙'],
    ['Do you think I ought to apply for this job? 💼', '¿Crees que debería postularme para este trabajo? 💼'],
    ['That’s a terrible thing to say. You ought to be ashamed of yourself. 😔', 'Eso es terrible de decir. Deberías avergonzarte de ti mismo. 😔'],
    ['She’s been studying hard for the exam, so she ought to pass. 📖', 'Ha estado estudiando mucho para el examen, así que debería pasar. 📖'],
]
 const subjuntive = [
    ['Why don’t you buy some nice clothes? –', '¿Por qué no compras ropa bonita? –'],
    ['I insisted he have dinner with us. 🍽️', 'Insistí en que él cenara con nosotros. 🍽️'],
    ['The doctor recommended that I rest for a few days. 💤', 'El doctor recomendó que descansara unos días. 💤'],
    ['John demanded that Lisa apologize to him. 😡', 'John exigió que Lisa se disculpara con él. 😡'],
    ['What do you suggest I do? 🤔', '¿Qué sugieres que haga? 🤔'],
    ['It’s essential that everyone be at work by 9:00 tomorrow morning. No exceptions. ⏰', 'Es esencial que todos estén en el trabajo para las 9:00 mañana. Sin excepciones. ⏰'],
    ['I’ts imperative that the government do something about healt care. 👩‍⚕️', 'Es imperativo que el gobierno haga algo sobre el cuidado de la salud. 👩‍⚕️'],
    ['It’s essential for everyone to be at work by 9:00 tomorrow morning. ⏰', 'Es esencial que todos estén en el trabajo para las 9:00 mañana. ⏰'],
    ['It’s imperative for the government to do somthing about health care. 👨‍⚕️', 'Es imperativo que el gobierno haga algo sobre el cuidado de la salud. 👨‍⚕️'],
    ['The doctor stongly recommended that I not go to work for two days. 💊', 'El doctor recomendó firmemente que no fuera al trabajo durante dos días. 💊'],
    ['It’s very important that you not miss this appointment with your eye doctor. 👁️', 'Es muy importante que no faltes a esta cita con tu oftalmólogo. 👁️'],
    ['I insist you come with us. 💼', 'Insisto en que vengas con nosotros. 💼'],
    ['They insisted I go with them. 👫', 'Insistieron en que fuera con ellos. 👫'],
    ['I insisted that something be done about the problem. 🛠️', 'Insistí en que se hiciera algo sobre el problema. 🛠️'],
    ['It’s essential that this medicine not be taken on an empty stomach. 💊', 'Es esencial que este medicamento no se tome con el estómago vacío. 💊'],
    ['The airline recommended we be at airport two hours before our flight. ✈️', 'La aerolínea recomendó que estuviéramos en el aeropuerto dos horas antes de nuestro vuelo. ✈️'],
    ['They insisted on paying for dinner. 🍽️', 'Insistieron en pagar la cena. 🍽️'],
    ['It is a beautiful evening, so I suggest going for a walk. 🌅', 'Es una hermosa tarde, así que sugiero dar un paseo. 🌅'],
    ['She suggested that he buy some new clothes. 👕', 'Ella sugirió que él comprara algunas ropas nuevas. 👕'],
    ['He insists on going with us. 👣', 'Insiste en ir con nosotros. 👣'],
]
 const hadBetter = [
    ['I have to meet Amy in 10 minutes. I’d better go now or I’ll be late. ⌚', 'Tengo que encontrarme con Amy en 10 minutos. Será mejor que vaya ahora o llegaré tarde. ⌚'],
    ['Do you think I should take an umbrella? –Yes, you’d better. It might rain. ☔', '¿Crees que debería llevar un paraguas? –Sí, será mejor. Podría llover. ☔'],
    ['We’d better stop for gas soon. The tank is almost empty. ⛽', 'Será mejor que paremos pronto para echar gasolina. El tanque está casi vacío. ⛽'],
    ['Are you going out tonight? –I’d better not. I’ve got a lot of work to do. 🌃', '¿Vas a salir esta noche? –Será mejor que no. Tengo mucho trabajo que hacer. 🌃'],
    ['You don’t look very well. You’d better not go to work today. 🤒', 'No te ves muy bien. Será mejor que no vayas al trabajo hoy. 🤒'],
    ['I’d better go now / I had better go now. 🚶‍♂️', 'Será mejor que me vaya ahora. 🚶‍♂️'],
    ['I’d better go to the bank now. 🏦', 'Será mejor que vaya al banco ahora. 🏦'],
    ['I’d better go to the store tomorrow. 🛒', 'Será mejor que vaya a la tienda mañana. 🛒'],
    ['It might rain. We’d better take an umbrella. ☂️', 'Podría llover. Será mejor que llevemos un paraguas. ☂️'],
    ['It’s cold. You’d better wear a coat when you go out. 🧥', 'Hace frío. Será mejor que te pongas un abrigo cuando salgas. 🧥'],
    ['You’re always at home. You should go out more often. 🏠', 'Siempre estás en casa. Deberías salir más a menudo. 🏠'],
    ['It’s a great movie. You should go and see it. 🎬', 'Es una gran película. Deberías ir a verla. 🎬'],
    ['The movie starts at 8:30. You’d better go now, or you’ll be late. ⏰', 'La película comienza a las 8:30. Será mejor que vayas ahora, o llegarás tarde. ⏰'],
    ['It’s time to go home. 🕒', 'Es hora de ir a casa. 🕒'],
    ['It’s time for us to go home. ⏰', 'Es hora de que nos vayamos a casa. ⏰'],
    ['It’s late. It’s time we went home. ⌚', 'Es tarde. Es hora de que nos vayamos a casa. ⌚'],
    ['It’s 10:00 and he’s still in bed. It’s time he got up. ⏰', 'Son las 10:00 y todavía está en la cama. Ya es hora de que se levante. ⏰'],
    ['It’s time you did something = You should have already done it or started it. ⌛', 'Ya es hora de que hagas algo = Deberías haberlo hecho o empezado ya. ⌛'],
    ['It’s time you changed the oil in the car. It hasn’t been changed in a long time. 🚗', 'Ya es hora de que cambies el aceite del coche. No se ha cambiado en mucho tiempo. 🚗'],
    ['The windows are very dirty. I think it’s time they were washed. 🪟', 'Las ventanas están muy sucias. Creo que ya es hora de que las laven. 🪟'],
    ['Jack is a great talker. But it’s about time he did something instead of just talking. 💬', 'Jack es un gran hablador. Pero ya es hora de que haga algo en lugar de solo hablar. 💬'],
]
const  would = [
    ['It would be nice to buy a new car, but we can’t afford it. 🚗', 'Sería bueno comprar un coche nuevo, pero no podemos pagarlo. 🚗'],
    ['I’d love to live by the ocean. 🌊', 'Me encantaría vivir junto al océano. 🌊'],
    ['Should I tell Chris what happened? –No, I wouldn’t say anything. 🤐', '¿Debería decirle a Chris lo que pasó? –No, no diría nada. 🤐'],
    ['They helped us a lot. I don’t know what we would have done without their help. 🤝', 'Nos ayudaron mucho. No sé qué habríamos hecho sin su ayuda. 🤝'],
    ['I didn’t tell Sam what happened. He wouldn’t have been pleased. 😒', 'No le conté a Sam lo que pasó. No habría estado contento. 😒'],
    ['I would call Sue, but I don’t have her number. 📞', 'Llamaría a Sue, pero no tengo su número. 📞'],
    ['I would have called Sue, but I didn’t have her number. 📱', 'Habría llamado a Sue, pero no tenía su número. 📱'],
    ['I’m not going to invite them to the party. They wouldn’t come anyway. 🎉', 'No los voy a invitar a la fiesta. De todos modos, no vendrían. 🎉'],
    ['I didn’t invite them to the party. They wouldn’t have come anyway. 🚫', 'No los invité a la fiesta. De todos modos, no habrían venido. 🚫'],
    ['I would call Sue if I had her number. 📞', 'Llamaría a Sue si tuviera su número. 📞'],
    ['I would have called Sue if I’d had her number. 📱', 'Habría llamado a Sue si hubiera tenido su número. 📱'],
    ['I’d stay a little longer, but I really have to go now. ⏰', 'Me quedaría un poco más, pero realmente tengo que irme ahora. ⏰'],
    ['I’d call Sue, but I don’t have her number. 📞', 'Llamaría a Sue, pero no tengo su número. 📞'],
    ['Tom said he’d call me on Sunday. 📅', 'Tom dijo que me llamaría el domingo. 📅'],
    ['Ann promised that she wouldn’t be late. ⏱️', 'Ann prometió que no llegaría tarde. ⏱️'],
    ['Liz was annoyed because her car wouldn’t start. 🚗', 'Liz estaba molesta porque su coche no arrancaba. 🚗'],
    ['I tried to warn him, but he wouldn’t listen to me. 🙉', 'Intenté advertirle, pero no me escuchaba. 🙉'],
    ['The car wouldn’t start. 🚙', 'El coche no arrancaba. 🚙'],
    ['When we were children, we lived by the ocean. In summer if the weather was nice, we would all get up early and go for a swim. 🌞', 'Cuando éramos niños, vivíamos junto al océano. En verano, si el clima era agradable, todos nos levantábamos temprano e íbamos a nadar. 🌞'],
    ['Whenever Richard was angry, he would walk out of the room. 🚶‍♂️', 'Siempre que Richard estaba enojado, salía de la habitación. 🚶‍♂️'],
]
const  can_could_would = [
    ['Can you wait a minute please? ⏳', '¿Puedes esperar un minuto, por favor? ⏳'],
    ['Could you wait a moment please? ⌛', '¿Podrías esperar un momento, por favor? ⌛'],
    ['Liz, can you do me a favor? 🙏', 'Liz, ¿puedes hacerme un favor? 🙏'],
    ['Excuse me, could you tell me how to get to the airport? ✈️', 'Disculpe, ¿podría decirme cómo llegar al aeropuerto? ✈️'],
    ['I wonder if you could help me. 🤔', 'Me pregunto si podrías ayudarme. 🤔'],
    ['Do you think you could lend me some money until next week? 💰', '¿Crees que podrías prestarme algo de dinero hasta la próxima semana? 💰'],
    ['Liz, will you do me a favor? 🙏', 'Liz, ¿me haces un favor? 🙏'],
    ['Would you please be quiet? I’m trying to concentrate. 🤫', '¿Podrías por favor guardar silencio? Estoy tratando de concentrarme. 🤫'],
    ['Can I have these postcards, please? 📬', '¿Puedo tener estas postales, por favor? 📬'],
    ['Could I have the salt please? 🧂', '¿Podría tener la sal, por favor? 🧂'],
    ['May I have these postcards, please? 📮', '¿Puedo tener estas postales, por favor? 📮'],
    ['Hello, can I speak to Tom please? 📞', 'Hola, ¿puedo hablar con Tom, por favor? 📞'],
    ['Could I use your phone? –Yes, of course. 📱', '¿Podría usar tu teléfono? –Sí, por supuesto. 📱'],
    ['Do you think I could borrow your bike? 🚲', '¿Crees que podría tomar prestada tu bicicleta? 🚲'],
    ['May I come in? –Yes, please do. 🚪', '¿Puedo entrar? –Sí, por favor. 🚪'],
    ['Do you mind if I use your phone? –No. Not at all. 📞', '¿Te importa si uso tu teléfono? –No, para nada. 📞'],
    ['Is it all right if I come in? –Yes, of course. 🚶‍♂️', '¿Está bien si entro? –Sí, por supuesto. 🚶‍♂️'],
    ['Can I get you a cup of coffee? –Yes, that would be very nice ☕', '¿Puedo traerte una taza de café? –Sí, eso sería muy agradable. ☕'],
    ['May I help you? –No, thanks. I’m being helped. 🤝', '¿Puedo ayudarte? –No, gracias. Ya me están ayudando. 🤝'],
    ['Would you like a cup of coffee? –Yes please. ☕', '¿Te gustaría una taza de café? –Sí, por favor. ☕'],
    ['Would you like to go to the movies with us tonight? –Yes, I’d love to. 🎬', '¿Te gustaría ir al cine con nosotros esta noche? –Sí, me encantaría. 🎬'],
    ['I’d like some information about hotels, please. ℹ️', 'Me gustaría información sobre hoteles, por favor. ℹ️'],
    ['I’d like to try on this jacket, please. 👕', 'Me gustaría probarme esta chaqueta, por favor. 👕'],
]

export { couldAndCouldHaveDone ,canCouldAndBeAbleTo  ,must, mayAndMight1, mayAndMight2, haveToAndMust, Should, subjuntive, hadBetter, would, can_could_would}