const pasive = [
    ['This house is pretty old. It was built in 1935. 🏠', 'Esta casa es bastante antigua. Fue construida en 1935. 🏠'],
    ['Two hundred people are employed by the company. 👥', 'Doscientas personas están empleadas por la empresa. 👥'],
    ['A lot of money was stolen in the robbery. 💰', 'Se robó mucho dinero en el robo. 💰'],
    ['Is this room cleaned every day? 🧹', '¿Se limpia esta habitación todos los días? 🧹'],
    ['Thai was built by my grandfather. 🏗️', 'Esta tailandesa fue construida por mi abuelo. 🏗️'],
    ['Two hundred people are employed by the company. 👥', 'Doscientas personas están empleadas por la empresa. 👥'],
    ['This room is cleaned everyday. 🧼', 'Esta habitación se limpia todos los días. 🧼'],
    ['Many accidents are caused by careless driving. 🚗', 'Muchos accidentes son causados por una conducción descuidada. 🚗'],
    ['I’m not often invited to parties. 🎉', 'No me invitan a menudo a fiestas. 🎉'],
    ['How is this word pronounced? 🗣️', '¿Cómo se pronuncia esta palabra? 🗣️'],
    ['We were woken up by a loud noise during the night. 🌙', 'Nos despertó un ruido fuerte durante la noche. 🌙'],
    ['Did you go to the party? –No, I wasn’t invited. 🎈', '¿Fuiste a la fiesta? –No, no fui invitado. 🎈'],
    ['This room will be cleaned later. 🧹', 'Esta habitación se limpiará más tarde. 🧹'],
    ['The situation is serious. Something must be done before it’s too late. ⚠️', 'La situación es seria. Algo debe hacerse antes de que sea demasiado tarde. ⚠️'],
    ['A mystery is something that can’t be explained. ❓', 'Un misterio es algo que no se puede explicar. ❓'],
    ['The music was very loud and could be heard from far away. 🔊', 'La música era muy fuerte y se podía escuchar desde lejos. 🔊'],
    ['A new supermarket is going to be built next year. 🏪', 'El próximo año se construirá un supermercado nuevo. 🏪'],
    ['Please go away. I want to be left alone. 🚶‍♂️', 'Por favor, vete. Quiero estar solo. 🚶‍♂️'],
    ['This room should have been cleaned. 🧹', 'Esta habitación debería haber sido limpiada. 🧹'],
    ['I haven’t received the letter yet. It might have been sent to the wrong address. 📬', 'Todavía no he recibido la carta. Puede que haya sido enviada a la dirección incorrecta. 📬'],
    ['If you had locked the car, it wouldn’t have been stolen. 🔐', 'Si hubieras cerrado con llave el coche, no lo habrían robado. 🔐'],
    ['There were some problems at first, but they seem to have been solved. ✅', 'Hubo algunos problemas al principio, pero parece que se han solucionado. ✅'],
    ['The room looks nice. It has been cleaned. 👍', 'La habitación se ve bien. Ha sido limpiada. 👍'],
    ['Have you heard? The concert has been canceled. 🎵', '¿Has escuchado? El concierto ha sido cancelado. 🎵'],
    ['Have you ever been bitten by a dog? 🐕', '¿Alguna vez te ha mordido un perro? 🐕'],
    ['Are you going to the party? –No, I haven’t been invited. 🎉', '¿Vas a la fiesta? –No, no me han invitado. 🎉'],
    ['The room looked nice. It had been cleaned. 👌', 'La habitación se veía bien. Había sido limpiada. 👌'],
    ['The vegetables didn’t taste very good. They had been cooked too long. 🥦', 'Las verduras no sabían muy bien. Se habían cocinado demasiado tiempo. 🥦'],
    ['The car was three years old but hadn’t been used very much. 🚗', 'El coche tenía tres años pero no había sido usado mucho. 🚗'],
    ['This room is being cleaned right now. 🧼', 'Esta habitación se está limpiando en este momento. 🧼'],
    ['There’s somebody walking behind us. I think we are being followed. 👀', 'Hay alguien caminando detrás de nosotros. Creo que nos están siguiendo. 👀'],
    ['Can I help you? –No, thank you. I’m being helped. 🤝', '¿Puedo ayudarte? –No, gracias. Ya estoy siendo ayudado. 🤝'],
    ['This room was being cleaned when I arrived. 🧹', 'Esta habitación se estaba limpiando cuando llegué. 🧹'],
    ['There was somebody walking behind us. We were being followed. 👣', 'Había alguien caminando detrás de nosotros. Nos estaban siguiendo. 👣'],
    ['The police were given the information. 🚓', 'La policía recibió la información. 🚓'],
    ['The information was given to the police. 📝', 'La información fue dada a la policía. 📝'],
    ['I was offered the job, but I refused it. 🤝', 'Me ofrecieron el trabajo, pero lo rechacé. 🤝'],
    ['You will be given plenty of time to decide. ⏳', 'Se te dará mucho tiempo para decidir. ⏳'],
    ['Have you been shown the new machine? 🔧', '¿Te han mostrado la nueva máquina? 🔧'],
    ['The men were paid $200 to do the work. 💰', 'A los hombres se les pagó $200 por hacer el trabajo. 💰'],
    ['I don’t like being told what to do. 🚫', 'No me gusta que me digan qué hacer. 🚫'],
    ['I remember being taken to the zoo when I was a child. 🦁', 'Recuerdo que me llevaron al zoológico cuando era niño. 🦁'],
    ['Steve hates being kept waiting. 😠', 'Steve odia que lo hagan esperar. 😠'],
    ['We managed to climb over the wall without being seen. 🧗‍♂️', 'Logramos trepar sobre la pared sin ser vistos. 🧗‍♂️'],
    ['I was born in Chicago. 🌆', 'Nací en Chicago. 🌆'],
    ['How many babies are born every day? 👶', '¿Cuántos bebés nacen todos los días? 👶'],
    ['There was a fight at the game, but nobody got hurt. 🥊', 'Hubo una pelea en el juego, pero nadie resultó herido. 🥊'],
    ["I don't often get invited to parties. 🎉", "No me invitan a menudo a fiestas. 🎉"],
    ["I'm surprised Ann didn't get offered the job. 😯", "Me sorprende que Ann no haya sido ofrecida el trabajo. 😯"],
    ['Jill is liked by everybody. ❤️', 'A todos les cae bien Jill. ❤️'],
    ['He was a mystery man. Very little was known about him. 🕵️‍♂️', 'Era un hombre misterioso. Se sabía muy poco sobre él. 🕵️‍♂️'],
    ['get married 💒', 'casarse 💒'],
    ['get divorced 💔', 'divorciarse 💔'],
    ['get dressed 👗', 'vestirse 👗'],
    ['get lost 🗺️', 'perderse 🗺️'],
    ['get changed 🔄', 'cambiarse 🔄'],    
]
const itissaidthat = [
    ['Nobody knows exactly how old he is but, It is said that he is 108 years old. 🕵️‍♂️', 'Nadie sabe exactamente cuántos años tiene, pero se dice que tiene 108 años. 🕵️‍♂️'],
    ['Cathay works very hard. It is said she works 16 hours a day. 👩‍💼', 'Cathay trabaja muy duro. Se dice que trabaja 16 horas al día. 👩‍💼'],
    ['The police are looking for a missing boy. It is believed that the boy is wearing a white sweater and blue jeans. 👮‍♂️', 'La policía está buscando a un niño desaparecido. Se cree que el niño lleva un suéter blanco y jeans azules. 👮‍♂️'],
    ['The strike started three weeks ago. It is expected that it will end soon. ⛔', 'La huelga comenzó hace tres semanas. Se espera que termine pronto. ⛔'],
    ['A friend of mine has been arrested. It is alleged that he hit a police officer. 🚓', 'Un amigo mío ha sido arrestado. Se alega que golpeó a un oficial de policía. 🚓'],
    ['The two houses belong to the same family. It is said that there is a secret tunnel between them. 🏠', 'Las dos casas pertenecen a la misma familia. Se dice que hay un túnel secreto entre ellas. 🏠'],
    ['It is reported that two people were injured in the explosion. 📰', 'Se informa que dos personas resultaron heridas en la explosión. 📰'],
    ['Two people are reported to have been injured in the explosion. 🚑', 'Se informa que dos personas resultaron heridas en la explosión. 🚑'],
    ['Let’s go and see that movie. It’s supposed to be good. 🎥', 'Vamos a ver esa película. Se supone que es buena. 🎥'],
    ['Mark is supposed to have hit a police officer, but I don’t believe it. 👊', 'Se supone que Mark golpeó a un oficial de policía, pero no lo creo. 👊'],
    ['The plan is supposed to be a secret, but everybody seems to know about it. 🤫', 'Se supone que el plan es secreto, pero parece que todos lo saben. 🤫'],
    ['What are you doing at work? You’re supposed to be on vacation. 🏖️', '¿Qué estás haciendo en el trabajo? Se supone que estás de vacaciones. 🏖️'],
    ['Jane was supposed to call me last night, but she didn’t. 📞', 'Jane debía llamarme anoche, pero no lo hizo. 📞'],
    ['Our guests were supposed to come at 7:30, but they were late. ⏰', 'Nuestros invitados debían venir a las 7:30, pero llegaron tarde. ⏰'],
    ['I’d better hurry. I’m supposed to meet Chris in 10 minutes. ⏱️', 'Más me vale apurarme. Se supone que debo encontrarme con Chris en 10 minutos. ⏱️'],
    ["You’re not supposed to park your car here. It’s private parking only. 🚗", "No se supone que estaciones tu auto aquí. Es solo estacionamiento privado. 🚗"],
    ["Mr. Bruno is much better after his operation, but he’s still not supposed to do any heavy work. 💼", "El Sr. Bruno está mucho mejor después de su operación, pero todavía no se supone que haga ningún trabajo pesado. 💼"],
]
const havesomethingdone = [
    ['Lisa had the roof repaired yesterday. 🔨', 'Lisa hizo reparar el techo ayer. 🔨'],
    ['Did you have your apartment painted? –No, I painted it myself. 🎨', '¿Hiciste pintar tu apartamento? –No, lo pinté yo mismo. 🎨'],
    ['Where did you have your hair cut? 💇', '¿Dónde te cortaste el cabello? 💇'],
    ['Our neighbor has just had air conditioning installed in her house. ❄️', 'Nuestra vecina acaba de instalar aire acondicionado en su casa. ❄️'],
    ['We are having the house painted this week. 🏠', 'Vamos a hacer pintar la casa esta semana. 🏠'],
    ['How often do you have your car serviced? 🚗', '¿Con qué frecuencia haces revisar tu coche? 🚗'],
    ['Why don’t you have that coat cleaned? 🧥', '¿Por qué no mandas limpiar ese abrigo? 🧥'],
    ['I don’t like having my picture taken. 📸', 'No me gusta que me tomen fotos. 📸'],
    ['When are you going to get the roof repaired? 🏠', '¿Cuándo vas a hacer reparar el techo? 🏠'],
    ['I think you should get your hair cut really short. 💇‍♂️', 'Creo que deberías cortarte mucho el cabello. 💇‍♂️'],
    ['Eric had his license taken away for driving too fast again and again. 🚗', 'A Eric le quitaron la licencia por conducir demasiado rápido una y otra vez. 🚗'],
    ['Eric got his licence taken away for driving too fast again and again. 🚓', 'A Eric le quitaron la licencia por conducir demasiado rápido una y otra vez. 🚓'],
    ['James got his passport stolen. 🛂', 'A James le robaron el pasaporte. 🛂'],
    ['Have you ever had your flight canceled? ✈️', '¿Alguna vez te han cancelado el vuelo? ✈️'],
]

export { pasive, itissaidthat, havesomethingdone}