// 21 Will 2

const willTwo = [
    ['Ann estará trabajando la próxima semana.', 'Ann is working next week.'],
    ['¿Vas a ver televisión esta noche?', 'Are you going to watch television tonight?'],
    ['Jill ha vivido en el extranjero durante mucho tiempo. Cuando regrese, encontrará muchos cambios aquí.', 'Jill has lived abroad for a long time. When she comes back, she’ll find a lot of changes here.'],
    ['¿Dónde estarás en esta misma fecha el próximo año? – Estaré en Japón.', 'Where will you be this time next year? – I’ll be in Japan.'],
    ['Ese plato está caliente. Si lo tocas, te quemarás.', 'That plate is hot. If you touch it, you’ll burn yourself.'],
    ['Tom no aprobará el examen. No ha estudiado lo suficiente.', 'Tom won’t pass the exam. He hasn’t studied hard enough.'],
    ['¿Cuándo descubrirás cómo te fue en el examen?', 'When will you find out how you did on the exam?'],
    ['Probablemente llegue tarde a casa esta noche.', 'I’ll probably be home late tonight.'],
    ['Espero que la prueba tome dos horas.', 'I expect the test will take two hours.'],
    ['No te preocupes por el examen. Estoy seguro de que aprobarás.', 'Don’t worry about the exam. I’m sure you’ll pass.'],
    ['¿Crees que a Sarah le gustará el regalo que le compramos?', 'Do you think Sarah will like the present we bought her?'],
    ['No creo que el examen sea muy difícil.', 'I don’t think the exam will be very difficult.'],
    ['Supongo que tus padres estarán cansados después de su viaje.', 'I guess your parents will be tired after their trip.'],
    ['¿Cuándo crees que Jan y Mark se casarán?', 'When do you suppose Jan and Mark will get married?'],
    ['Dudo que necesites un abrigo pesado en Las Vegas. Por lo general, hace calor allí.', 'I doubt you’ll need a heavy coat in Las Vegas. It’s usually warm there.'],
    ['Me preocupo por esas personas que perdieron sus trabajos. Me pregunto qué les sucederá.', 'I worry about those people who lost their jobs. I wonder what will happen to them.'],
    ['Espero que Kate apruebe el examen.', 'I hope Kate passes the exam.'],
    ['Espero que no llueva mañana.', 'I hope it doesn’t rain tomorrow.'],
    ['Diane no está libre el sábado. Está trabajando. (Está trabajando es correcto)', 'Diane isn’t free on Saturday. She’s working. (She’s working is correct)'],
    ['Voy a una fiesta mañana por la noche. ¿Quieres venir también?', 'I’m going to a party tomorrow night. Would you like to come too?'],
    ['Creo que Amy conseguirá el trabajo. Ella tiene mucha experiencia.', 'I think Amy will get the job. She has a lot of experience.'],
    ['No puedo encontrarme contigo esta noche. Un amigo mío vendrá.', 'I can’t meet you tonight. A friend of mine is coming over.'],
    ['¿Ya decidieron dónde ir de vacaciones? – Sí, iremos a Italia.', 'Have you decided where to go on vacation? – Yes, we are going to Italy.'],
    ['No tengas miedo del perro. No te hará daño.', 'Don’t be afraid of the dog. It won’t hurt you.'],
    ['No te preocupes por el examen. Estoy seguro de que aprobarás.', 'Don’t worry about the exam. I’m sure you’ll pass.'],
    ['¿Por qué no pruebas esta chaqueta? Te quedará bien.', 'Why don’t you try on this jacket? It will look nice on you.'],
    ['Quiero que conozcas a Brandon en algún momento. Creo que te caerá bien.', 'I want you to meet Brandon sometime. I think you’ll like him.'],
    ['Está lloviendo. No salgas. Te mojarás.', 'It’s raining. Don’t go out. You will get wet.'],
    ['¿Crees que las personas vivirán más tiempo en el futuro?', 'Do you think people will live longer in the future?'],
    ['Adiós. Estoy seguro de que nos veremos pronto.', 'Goodbye. I’m sure we will see each other again soon.'],
    ['Invité a Sue a la fiesta, pero no creo que venga.', 'I invited Sue to the party, but I don’t think she will come.'],
    ['Cuando terminen la nueva carretera, espero que mi viaje al trabajo lleve menos tiempo.', 'When the new road is finished, I expect that my trip to work will take less time.'],
    ['¿Puedes esperarme? – No tardaré mucho.', 'Can you wait for me? – I won’t be very long.'],
    ['No necesitas llevar un paraguas. No lloverá.', 'You don’t need to take an umbrella along. It won’t rain.'],
    ['Si no comes nada ahora, tendrás hambre más tarde.', 'If you don’t eat anything now, you will be hungry later.'],
    ['Lo siento por lo que pasó ayer. No volverá a suceder.', 'I’m sorry about what happened yesterday. It won’t happen again.'],
    ['¡Tengo unas noticias increíbles! No creerás lo que sucedió.', 'I’ve got some incredible news! You won’t believe what happened.'],
    ['No hay más pan. Supongo que tendremos que ir de compras antes de comer.', 'There’s no more bread. I guess we will have to go shopping before we eat.'],
    ['No le pidas consejo a Amanda. No sabrá qué hacer.', 'Don’t ask Amanda for advice. She won’t know what to do.'],
    ['A Jack no le gustan las multitudes. No creo que venga con nosotros a la fiesta.', 'Jack doesn’t like crowds. I don’t think he will come with us to the party.'],
    ['Le compré un regalo a Rosa. ¿Crees que le gustará?', 'I bought Rosa a present. Do you think she’ll like it?'],
    ['El cielo está oscuro y nublado. ¿Crees que lloverá?', 'The sky is dark and cloudy. Do you think it will rain?'],
    ['La reunión aún está en marcha. ¿Cuándo crees que terminará?', 'The meeting is still going on. When do you think it will end?'],
    ['Mi auto necesita ser reparado. ¿Cuánto crees que costará?', 'My car needs to be fixed. How much do you think it will cost?'],
    ['Sally y David están enamorados. ¿Crees que se casarán?', 'Sally and David are in love. Do you think they will get married?'],
    ['Me estoy yendo ahora. – Bien, ¿a qué hora crees que volverás?', 'I’m going out now. – OK, what time do you think you will be back?'],
    ['El futuro es incierto. ¿Qué crees que sucederá?', 'The future is uncertain. What do you think will happen?'],
  ];
  

export default willTwo;