
const reportedSpeech  = [
    ['Tom said that he was feeling sick. 🤒', 'Tom dijo que se sentía enfermo. 🤒'],
    ['I told her that I didn’t have any money. 💰', 'Le dije que no tenía dinero. 💰'],
    ['Jenny said that her parents were fine. 👨‍👩‍👧‍👦', 'Jenny dijo que sus padres estaban bien. 👨‍👩‍👧‍👦'],
    ['She said that she was going to learn to drive. 🚗', 'Ella dijo que iba a aprender a conducir. 🚗'],
    ['She said that she wanted to buy a car. 🚘', 'Ella dijo que quería comprar un coche. 🚘'],
    ['She said that John had quit his job. 👨‍💼', 'Ella dijo que John había renunciado a su trabajo. 👨‍💼'],
    ['She said that she couldn’t come to the party on Friday. 🎉', 'Ella dijo que no podía venir a la fiesta del viernes. 🎉'],
    ['She said she didn’t have much free time. ⏰', 'Ella dijo que no tenía mucho tiempo libre. ⏰'],
    ['She said that she was going away for a few days and would call me when she got back. 📞', 'Ella dijo que se iba por unos días y me llamaría cuando regresara. 📞'],
    ['Tom said that he woke up feeling sick, so he didn’t go to work. 🤒', 'Tom dijo que se despertó sintiéndose enfermo, así que no fue al trabajo. 🤒'],
    ['Mike said that he had woken up feeling sick, so he hadn’t gone to work. 🤢', 'Mike dijo que se despertó sintiéndose enfermo, así que no había ido al trabajo. 🤢'],
    ['Tom said that his new job is very interesting. 💼', 'Tom dijo que su nuevo trabajo es muy interesante. 💼'],
    ['Ann told me that she wants to go to South America next year. 🌎', 'Ann me dijo que quiere ir a Sudamérica el próximo año. 🌎'],
    ['Paul left the room suddenly. He said he had to go. 🚪', 'Paul salió de la habitación repentinamente. Dijo que tenía que irse. 🚪'],
    ['Sonia said you were in the hospital. 🏥', 'Sonia dijo que estabas en el hospital. 🏥'],
    ['What did you tell the police? 🚔', '¿Qué le dijiste a la policía? 🚔'],
    ['Sonia told me that you were in the hospital. 🏥', 'Sonia me dijo que estabas en el hospital. 🏥'],
    ['Ann said goodbye to me and left. 👋', 'Ann se despidió de mí y se fue. 👋'],
    ['What did you say to the police? 🚔', '¿Qué dijiste a la policía? 🚔'],
    ['The doctor told me to stay in bed for a few days. 🛌', 'El médico me dijo que me quedara en la cama por unos días. 🛌'],
    ['I told Jim not to shout. 📣', 'Le dije a Jim que no gritara. 📣'],
    ['Jackie asked me not to tell anybody what happened. 🤫', 'Jackie me pidió que no le dijera a nadie lo que pasó. 🤫'],
    ['Jackie said not to tell anyone. 🤐', 'Jackie dijo que no le dijera a nadie. 🤐'],
]
export default reportedSpeech
